# Generated by Django 4.1.3 on 2022-12-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='a',
            field=models.Field(null=True),
        ),
    ]
