# Generated by Django 4.1.3 on 2022-12-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='a',
        ),
    ]
